[WC-2546]: Fix atlas sidebar when using React Mode
mendix/atlas pull request #148
Opened 2024-09-04 09:55 UTC by samuelreichert

2024-09-04 18:36 UTC, gjulivan submitted a review, later dismissed

2024-09-04 18:37 UTC, gjulivan commented
please check if this is also still works fine with dojo client

2024-09-06 14:00 UTC, leonardomendix approved these changes

2024-09-06 14:09 UTC, leonardomendix requested changes
Noticed one small issue when using subitems in the navigation.

2024-09-10 14:14 UTC, leonardomendix submitted a review, later dismissed

2024-09-11 07:54 UTC, gjulivan approved these changes

2024-09-12 07:24 UTC, leonardomendix approved these changes

2024-09-12 07:25 UTC, iobuhov approved these changes

2024-09-12 07:28 UTC, merged