[WC-1900]: Update PublishMarketplace check tag step
mendix/atlas pull request #53
Opened 2023-07-11 09:01 UTC by samuelreichert

2023-07-18 11:20 UTC, iobuhov requested changes
I'm looking at this try/catch and I think it has no sense as we already throwing all errros. So, please, remove try catch.

2023-07-18 11:46 UTC, leonardomendix commented
I need to update the Atlas Design System test project, so don't worry about Atlas's tests failing now.

2023-07-19 12:28 UTC, iobuhov approved these changes

2023-07-19 12:35 UTC, rahmanunver approved these changes

2023-07-19 12:35 UTC, merged