Wc 2022 combobox internal release finalize
mendix/atlas pull request #66
Opened 2023-09-04 00:25 UTC by gjulivan

update form control style to support new combobox.

2023-09-04 07:50 UTC, iobuhov commented on packages/atlas-core/CHANGELOG.md
> +-   We added focus-within style to .form-control.
```suggestion
-   We improved styles for form controls when they are focused.
```

2023-09-04 07:58 UTC, iobuhov requested changes

2023-09-04 07:58 UTC, iobuhov commented on packages/atlas-core/CHANGELOG.md
> +-   We added focus-within style to .form-control.
Please, add also header `## Added`

2023-09-07 07:39 UTC, iobuhov approved these changes

2023-09-08 10:13 UTC, samuelreichert approved these changes
LGTM! 🚀

2023-09-08 10:14 UTC, merged